06_django_advance/03_IMAGE_UPLOAD/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

06_django_advance/03_IMAGE_UPLOAD/image_upload/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings  # MASTER_APP/settings.py

urlpatterns = [
    path('admin/', admin.site.urls),
    path('newsfeed/', include('sns.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

06_django_advance/03_IMAGE_UPLOAD/sns/urls.py
from django.urls import path
from . import views

app_name = 'sns'

urlpatterns = [
    path('', views.posting_list, name='posting_list'),
    path('<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('create/', views.create_posting, name='create_posting'),
    path('<int:posting_id>/delete', views.delete_posting, name='delete_posting'),
    path('<int:posting_id>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:posting_id>/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('<int:posting_id>/like/', views.toggle_like, name='like'),
]

06_django_advance/03_IMAGE_UPLOAD/accounts/models.py
from django.db import models

# Create your models here.

06_django_advance/03_IMAGE_UPLOAD/sns/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from faker import Faker

"""
$ python manage.py migrate <APP_NAME> zero
$ rm <APP_NAME>/migrations/0*
"""

f = Faker()

class Posting(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_postings', blank=True)
    content = models.TextField()
    icon = models.CharField(max_length=30, default='')
    image = models.ImageField(blank=True)  # $ pip install pillow
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at', ]   # created_at 을 descending 내림차순으로.

    def get_absolute_url(self):  # Detail 페이지를 쓸 거라면 만들어요.
        return reverse("sns:posting_detail", kwargs={"posting_id": self.pk})
    
    def __str__(self):
        return f'{self.pk}: {self.content[:20]}'

    @classmethod
    def dummy(cls, n):
        for _ in range(n):
            cls.objects.create(
                user_id=1,
                content=f.sentence(),
                icon='fas fa-angrycreative'
            )


class Comment(models.Model):
    # related_name 이 없으면, posting.comment_set / 아래아 같다면, posting.comments
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['created_at']
    
    @classmethod
    def dummy(cls, n, posting_id):
        for _ in range(n):
            cls.objects.create(
                user_id=1,
                posting_id=posting_id,
                content=f.sentence(),
            )
    
    def __str__(self):
        return f'{self.id}: {self.content[:10]}'

06_django_advance/03_IMAGE_UPLOAD/sns/forms.py
from django import forms
from .models import Posting, Comment

class PostingModelForm(forms.ModelForm):  # data의 입력과 검증 & HTML 
    content = forms.CharField(min_length=2)
    
    class Meta:
        model = Posting
        fields = ('content', 'image', 'icon')


class CommentModelForm(forms.ModelForm):
    content = forms.CharField(min_length=2, max_length=200)

    class Meta:
        model = Comment
        fields = ('content',)

06_django_advance/03_IMAGE_UPLOAD/accounts/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout


@require_http_methods(['GET', 'POST'])
def signup(request):  # new_user
    # 사용자가 회원가입할 데이터를 보냈다면,
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('sns:posting_list')

    else:  # 사용자가 회원가입 HTML 을 달라는 뜻
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', {
        'form': form,
    })


@require_http_methods(['GET', 'POST'])
def login(request):
    # 사용자 login 한 상태라면, 무시
    if request.user.is_authenticated:
        return redirect('sns:posting_list')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('sns:posting_list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {
        'form': form,
    })


def logout(request):
    auth_logout(request)
    return redirect('sns:posting_list')

06_django_advance/03_IMAGE_UPLOAD/sns/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.contrib.auth.decorators import login_required

from .models import Posting, Comment
from .forms import PostingModelForm, CommentModelForm


@require_GET
def posting_list(request):
    postings = Posting.objects.all()
    return render(request, 'sns/posting_list.html', {
        'postings': postings,
    })


@login_required
@require_GET
def posting_detail(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comments = posting.comments.all()  # posting.comment_set 이 아닌 이유는 Model => related_name
    is_like = True if posting.like_users.filter(id=request.user.id).exists() else False
    return render(request, 'sns/posting_detail.html', {
        'posting': posting,
        'comments': comments,
        'is_like': is_like,
    })


@login_required
@require_POST
def create_posting(request):
    form = PostingModelForm(request.POST, request.FILES)  # 검증 & 저장 준비
    if form.is_valid():  # 검증!
        posting = form.save(commit=False)  # 저장 => Posting 객체 return
        posting.user = request.user  # anonymous? => 그럴리 없음
        posting.save()
        return redirect(posting)  # 성공하면 detail page
    else:
        return redirect('sns:posting_list')  # 실패하면 list page


@login_required
@require_POST
def delete_posting(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    if request.user == posting.user:
        posting.delete()
    return redirect('sns:posting_list')


@login_required
@require_POST
def create_comment(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    form = CommentModelForm(request.POST)  # content 만 값을 확인 
    if form.is_valid():  # content 만 값을 검증
        comment = form.save(commit=False)  # 아직 posting_id 가 비어있기 때문에, 저장하는 '척' 만 하고 Comment 객체 return
        comment.posting = posting  # comment.posting_id = posting.id
        comment.user = request.user
        comment.save()
    return redirect(posting)


@login_required
@require_POST
def delete_comment(request, posting_id, comment_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect(posting)


@login_required
@require_POST
def toggle_like(request, posting_id):
    user = request.user
    posting = get_object_or_404(Posting, id=posting_id)
    # user.like_postings.add(posting)  # 같은 의미
    # if user in posting.like_users.all():  # Python == 느림
    if posting.like_users.filter(id=user.id).exists():
        posting.like_users.remove(user)  # Delete
    else:
        posting.like_users.add(user)  # Create
    return redirect(posting)

06_django_advance/03_IMAGE_UPLOAD/accounts/templates/accounts/_form.html
{% load bootstrap4 %}

<form method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">Submit</button>
  {% endbuttons %}
</form>

06_django_advance/03_IMAGE_UPLOAD/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- FonteAwesome icon set -->
    <script src="https://kit.fontawesome.com/557ed3dfa5.js" crossorigin="anonymous"></script>

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  <!-- Bootstrap JS & Jquery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>    
</body>
</html>

06_django_advance/03_IMAGE_UPLOAD/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block title %}Login{% endblock %}

{% block body %}
{% include 'accounts/_form.html' %}
{% endblock %}

06_django_advance/03_IMAGE_UPLOAD/accounts/templates/accounts/signup.html
{% extends 'accounts/base.html' %}

{% block title %}Sign up{% endblock %}

{% block body %}
{% include 'accounts/_form.html' %}
{% endblock %}

06_django_advance/03_IMAGE_UPLOAD/sns/templates/sns/_card.html
<article class="card mb-3">
  <a href="{{ posting.get_absolute_url }}">
    {% if posting.image %}
        <img src="{{ posting.image.url }}" alt="{{ posting.image }}" class="card-img-top image-fluid">
    {% else %}
        <img src="https://picsum.photos/200/300" alt="random-image-{{ forloop.counter }}" class="card-img-top image-fluid">
    {% endif %}
  </a>
  <div class="card-body">
    <i class="fa-2x {{ posting.icon }}"></i>
  </div>
</article>

06_django_advance/03_IMAGE_UPLOAD/sns/templates/sns/_comment.html
<div class="col-12 col-md-6">

  <div class="card mb-2">
    <div class="card-body">
      <form action="{% url 'sns:create_comment' posting.id %}" method="POST">
        {% csrf_token %}
        <label for="comment"><strong>{{ request.user }}</strong>, leave comment</label>
        <input type="text" name="content" id="comment" class="form-control" autofocus>
      </form>
    </div>
  </div>

  <div class="card">
    <ul class="list-group list-group-flush">
      {% if comments %}
      {% for comment in comments %}
      <li class="list-group-item mb-1">
        <div class="row">
          <div class="col-10">
            <strong>{{ comment.user }}</strong>: {{ comment.content }}
          </div>
          <div class="col-2">
            {% if request.user == comment.user %}
            <form action="{% url 'sns:delete_comment' posting.id comment.id %}" method="POST">
              {% csrf_token %}
              <button>
                <i class="fas fa-trash"></i>
              </button>
            </form>
            {% endif %}
          </div>
        </div>
      </li>
      {% endfor %}
      {% else %}
      <li class="list-group-item mb-1">No comments yet..</li>
      {% endif %}
    </ul>
  </div>
</div>

06_django_advance/03_IMAGE_UPLOAD/sns/templates/sns/_header.html
{% if user.is_authenticated %}
<header class="mt-4 mb-4">
  <form action="{% url 'sns:create_posting' %}" enctype="multipart/form-data" method="POST">
    {% csrf_token %}

    <div class="form-row align-items-center">
      
      <!-- icon select tag -->
      <div class="col-auto my-1">
        <label for="icon" class="sr-only">icon</label>
        <select name="icon" id="icon" class="custom-select mr-sm-2">
          <option value="fas fa-question">?</option>
          <option value="far fa-smile">:)</option>
          <option value="far fa-angry">:(</option>
          <option value="far fa-smile-wink">;)</option>
          <option value="fab fa-angrycreative">flex</option>
        </select>
      </div>

      <!-- content input -->
      <div class="col-sm-6 my-1">
        <label for="content" class="sr-only">content</label>
        <input id="content" type="text" name="content" class="form-control" placeholder="feels like.."> 
      </div>

      <!-- image file input -->
      <div class="col-sm-4 my-1 input-group">
        <div class="input-group-prepend">
          <span class="input-group-text">Upload</span>
        </div>

        <div class="custom-file">
          <input id="image" class="custom-file-input" name="image" type="file" accept="image/*">
          <label for="image" class="custom-file-label">Choose image</label>
        </div>
      </div>

      <!-- submit button -->
      <div class="col-auto my-1">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>

    </div>
  </form>
</header>
{% endif %}

06_django_advance/03_IMAGE_UPLOAD/sns/templates/sns/_navbar.html
<nav class="mb-4">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a href="{% url 'sns:posting_list'%}" class="nav-link {% block list %}{% endblock %}">SNS</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% block detail %}{% endblock %}" aria-disabled="true">Detail</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item">
      <a href="{% url 'accounts:logout' %}" class="nav-link">Logout</a>
    </li>
    {% else %}
    <li class="nav-item">
      <a href="{% url 'accounts:signup' %}" class="nav-link">Signup</a>
    </li>
    <li class="nav-item">
      <a href="{% url 'accounts:login' %}" class="nav-link">Login</a>
    </li>
    {% endif %}
  </ul>
</nav>

06_django_advance/03_IMAGE_UPLOAD/sns/templates/sns/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <style>
    {% comment %} body {
      background-color: #353C51!important;
    } {% endcomment %}
  </style>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- FonteAwesome icon set -->
  <script src="https://kit.fontawesome.com/557ed3dfa5.js" crossorigin="anonymous"></script>
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
  {% include 'sns/_navbar.html' %}

  <div class="container">
    {% block body %}
    {% endblock body %}
  </div>

  <!-- Bootstrap JS & Jquery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

06_django_advance/03_IMAGE_UPLOAD/sns/templates/sns/posting_detail.html
{% extends 'sns/base.html' %}

{% block title %}{% endblock %}

{% block detail %}active{% endblock %}

{% block body %}
<div class="row mt-3">

  <div class="col-12 col-md-6">
    <div class="card">
      {% if posting.image %}
      <img class="card-img-top image-fluid" src="{{ posting.image.url }}" alt="{{ posting.image }}">
      {% else %}
      <img class="card-img-top image-fluid" src="https://picsum.photos/400/200" alt="random-image">
      {% endif %}

      <div class="card-body">
        <div class="row">
          <div class="col-2">
            <i class="{{ posting.icon }} fa-2x"></i>
          </div>
          <div class="col-6">
            <small>{{ posting.like_users.count }} 명이 좋아합니다.</small>
          </div>
          <div class="col-2">
            <form action="{% url 'sns:like' posting.id %}" method="POST">
              {% csrf_token %}
              <button>
              {% if is_like %}
                Dislike
              {% else %}
                Like
              {% endif %}
              </button>
            </form>
          </div>
        </div>
        <i class="{{ posting.icon }} fa-2x"></i>
        <hr>
        <div class="row">
          <div class="col-10">
            <p class="card-text"><strong>{{ posting.user }}</strong></p>
            <p class="card-text">{{ posting.content }}</p>
          </div>
          <div class="col-2">
            {% if user == posting.user %}
            <form action="{% url 'sns:delete_posting' posting.id %}" method="POST">
              {% csrf_token %}
              <button>
                <i class="fas fa-trash"></i>
              </button>
            </form>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

  {% include 'sns/_comment.html' %}

</div>
{% endblock %}

06_django_advance/03_IMAGE_UPLOAD/sns/templates/sns/posting_list.html
{% extends 'sns/base.html' %}

{% block title %}SNS list{% endblock %}

{% block list %}active{% endblock %}

{% block body %}
{% include 'sns/_header.html' %}

{% if postings %}
<section class="card-columns">
  {% for posting in postings %}
  {% include 'sns/_card.html' %}
  {% endfor %}
</section>
{% endif %}
{% endblock %}