06_django_advance/04_INSTAGRAM/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    path('user_page/<int:user_id>/', views.user_page, name='user_page'),
    path('follow/<int:user_id>/', views.follow, name='follow'),
]

06_django_advance/04_INSTAGRAM/instagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('insta/', include('postings.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

06_django_advance/04_INSTAGRAM/postings/urls.py
from django.urls import path
from . import views

app_name = 'postings'

# insta/
urlpatterns = [
    path('', views.posting_list, name='posting_list'),
    path('<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('create/', views.create_posting, name='create_posting'),
    path('<int:posting_id>/update/', views.update_posting, name='update_posting'),
    path('<int:posting_id>/delete/', views.delete_posting, name='delete_posting'),

    path('<int:posting_id>/comments/create/', views.create_comment, name='create_comment'),

    path('<int:posting_id>/like/', views.toggle_like, name='like'),
]

06_django_advance/04_INSTAGRAM/postings/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django_extensions.db.models import TimeStampedModel
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit

User = get_user_model()

class HashTag(TimeStampedModel):  # TimeStampedModel은 created와 modified가 저절로 생김
    content = models.CharField(max_length=20, unique=True)

class Posting(TimeStampedModel):
    like_users = models.ManyToManyField(User, related_name='like_posts')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='postings')
    hashtags = models.ManyToManyField(HashTag, blank=True, related_name='postings')
    content = models.CharField(max_length=140)

    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse("postings:posting_detail", kwargs={"posting_id": self.pk})
    

class Image(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE, related_name='images')
    file = ProcessedImageField(
        processors=[ResizeToFit(600, 600, mat_color=(45,45,45))],  # 수정
        upload_to='postings/images',
        format='JPEG',
        options={'quality': 90},
    )

# p.image_set.all()  => related_name이 default값
# p.images.all()  => related_name='images'

class Comment(TimeStampedModel):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=140)

06_django_advance/04_INSTAGRAM/postings/forms.py
from django import forms
from .models import Posting, Comment, Image

class PostingForm(forms.ModelForm):
    class Meta:
        model = Posting
        fields = ('content',)

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('file',)
        widgets = {
            'file': forms.FileInput(attrs={'multiple':True})
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

06_django_advance/04_INSTAGRAM/postings/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_GET, require_http_methods, require_POST
from django.http import JsonResponse, HttpResponseBadRequest

from .forms import PostingForm, ImageForm, CommentForm
from .models import Posting, Comment, HashTag, Image


@require_GET
def posting_detail(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comment_form = CommentForm()
    is_like = posting.like_users.filter(id=request.user.id).exists()

    return render(request, 'postings/posting_detail.html', {
        'posting': posting,
        'comment_form': comment_form,
        'is_like': is_like,
    })

@require_GET
def posting_list(request):
    postings = Posting.objects.all()
    return render(request, 'postings/posting_list.html', {
        'postings': postings,
    })

@login_required
@require_http_methods(['GET', 'POST'])
def create_posting(request):
    images = request.FILES.getlist('file')
    if request.method == 'POST':
        posting_form = PostingForm(request.POST)
        if posting_form.is_valid() and len(images) <= 5:
            posting = posting_form.save(commit=False)
            posting.author = request.user
            posting.save()

            words = posting.content.split()
            for word in words:
                if word[0] == '#':
                    tag = HashTag.objects.get_or_create(content=word)  # get_or_create 의 return == list
                    posting.hashtags.add(tag[0])

            for image in images:
                request.FILES['file'] = image
                image_form = ImageForm(files=request.FILES)  # Form류는 request로 시작하는 객체여야만 사용 가능.
                if image_form.is_valid():
                    image = image_form.save(commit=False)
                    image.posting = posting
                    image.save()
            return redirect(posting)

    else:
        posting_form = PostingForm()
        image_form = ImageForm()
    return render(request, 'postings/posting_form.html', {
        'posting_form': posting_form,
        'image_form': image_form,
    })
    
@login_required
@require_http_methods(['GET', 'POST'])
def update_posting(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    if posting.author == request.user:
        if request.method == 'POST':
            posting_form = PostingForm(request.POST, instance=posting)
            if posting_form.is_valid():
                posting = posting_form.save()
                return redirect(posting)
        else:
            posting_form = PostingForm(instance=posting)
    else:
        return redirect(posting)
    return render(request, 'postings/posting_form.html', {
        'posting_form': posting_form,
    })

@login_required
@require_POST
def delete_posting(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    posting.delete()
    return redirect('postings:posting_list')


@login_required
@require_POST
def create_comment(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.author = request.user
        comment.posting = posting
        comment.save()
    return redirect(posting)


@login_required
@require_POST
def toggle_like(request, posting_id):
    if request.is_ajax:
        posting = get_object_or_404(Posting, id=posting_id)
        user = request.user

        # 좋아요를 누른 user 라면,
        if posting.like_users.filter(id=user.id).exists():
            posting.like_users.remove(user)
            liked = False
        else:
            posting.like_users.add(user)
            liked = True
        
        context = {'liked': liked, 'posting_id': posting.id, 'user_id': user.id}

        return JsonResponse(context)
    else:
        HttpResponseBadRequest()

06_django_advance/04_INSTAGRAM/postings/templates/postings/_comment.html
{% load bootstrap4 %}
<div class="card-body">
    <div class="card-footer">
        <form action="{% url 'postings:create_comment' posting.id %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            {% buttons %}
            <input type="submit" value="게시" class="btn btn-primary">
            {% endbuttons %}
        </form>
    </div>
    {% for comment in posting.comments.all %}
    <p class="card-text"><strong>{{ comment.author }}</strong> {{ comment.content }}</p>
    {% empty %}
    <p class="card-text">댓글이 없습니다.</p>
    {% endfor %}
</div>

06_django_advance/04_INSTAGRAM/postings/templates/postings/_posting.html
<div class="card my-3">
	{% if posting.images %}
	<div id="posting{{posting.id}}" class="carousel slide carousel-fade" data-ride="carousel">
		<div class="carousel-inner">
			{% for image in posting.images.all %}
			<div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
				<img src="{{ image.file.url }}" class="d-block w-100">
			</div>
			{% endfor %}
		</div>
		<a class="carousel-control-prev" href="#posting{{posting.id}}" role="button" data-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next" href="#posting{{posting.id}}" role="button" data-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>
	{% else %}
	<img src="..." alt="..." class="card-img-top" />
	{% endif %}
	<div class="card-body">
		{% comment %} <form action="{% url 'postings:like' posting.id %}" method="POST">
			{% csrf_token %} {% endcomment %}
			<button style="border:0; background: none;">
				<i class="{% if is_like %}fas{% else %}far{% endif %} fa-heart js-like-button" data-id="{{ posting.id }}"
					style="color:crimson"></i>

			</button>
		{% comment %} </form> {% endcomment %}

		<p class="card-text">{{posting.content}}</p>
		<a href="{% url 'postings:update_posting' posting.id %}" class="btn btn-warning">수정</a>
	</div>
</div>

{% block custom_script %}
{% endblock %}

06_django_advance/04_INSTAGRAM/postings/templates/postings/posting_detail.html
{% extends 'base.html' %}
{% block body %}
{% include 'postings/_posting.html' %}
{% include 'postings/_comment.html' %}
{% endblock %}

06_django_advance/04_INSTAGRAM/postings/templates/postings/posting_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form posting_form %}
    {% if image_form %}
    {% bootstrap_form image_form show_label=False %}
    {% endif %}
    {% buttons %}
    <button class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>

{% endblock %}

06_django_advance/04_INSTAGRAM/postings/templates/postings/posting_list.html
{% extends 'base.html' %}
{% block body %}
<div class="card-columns">
{% for posting in postings %}
<a href="{% url 'postings:posting_detail' posting.id %}">
    {% include 'postings/_posting.html' %}
</a>
{% endfor %}
</div>
{% endblock %}