06_django_advance/02_MY_RECAP/classroom/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'classroom'

urlpatterns = [
    path('', views.index),
    path('students/', views.lists, name='lists'),
    path('students/new/', views.new, name='new'),
    path('students/create/', views.create, name='create'),
    path('students/<int:num>/', views.detail, name='detail'),
    path('students/<int:num>/edit/', views.edit, name='edit'),
    path('students/<int:num>/update/', views.update, name='update'),
    path('students/<int:num>/delete/', views.delete, name='delete'),
]

06_django_advance/02_MY_RECAP/my_recap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/', include('classroom.urls')),
]

06_django_advance/02_MY_RECAP/classroom/models.py
from django.db import models


# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=10)
    age = models.IntegerField()
    major = models.TextField()

06_django_advance/02_MY_RECAP/classroom/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST
from .models import Student


# Create your views here.
def index(request):
    return render(request, 'classroom/index.html')


def lists(request):
    students = Student.objects.all()
    context = {'students': students}
    return render(request, 'classroom/lists.html', context)


def new(request):
    return render(request, 'classroom/new.html')


@require_POST
def create(request):
    student = Student()
    student.name = request.POST.get('name')
    student.age = request.POST.get('age')
    student.major = request.POST.get('major')
    student.save()
    return redirect(f'/classroom/students/{student.id}/')


def detail(request, num):
    student = get_object_or_404(Student, id=num)
    context = {'student': student}
    return render(request, 'classroom/detail.html', context)


def edit(request, num):
    student = Student.objects.get(id=num)
    context = {'student': student}
    return render(request, 'classroom/edit.html', context)


@require_POST
def update(request, num):
    student = Student.objects.get(id=num)
    student.name = request.POST.get('name')
    student.age = request.POST.get('age')
    student.major = request.POST.get('major')
    student.save()
    return redirect(f'/classroom/students/{student.id}/')


@require_POST
def delete(request, num):
    student = Student.objects.get(id=num)
    student.delete()
    return redirect('/classroom/students/')

06_django_advance/02_MY_RECAP/classroom/templates/classroom/detail.html
{% extends 'classroom/base.html' %}

{% block title %}{{ student.id }} detail{% endblock %}

{% block body %}
    {{student.id}} | {{student.name}} | {{student.age}} | {{student.major}}
    <div>
        <a href="{% url 'classroom:lists' %}"><button>lists</button></a>
    </div>
    <div>
        <a href="{% url 'classroom:edit' student.id %}"><button>edit</button></a>
    </div>
    <div>
        <form action="{% url 'classroom:delete' student.id %}" method="POST">
            {% csrf_token %}
            <input id="deleteButton" type="submit" value="delete">
        </form>
    </div>
{% endblock %}

06_django_advance/02_MY_RECAP/classroom/templates/classroom/edit.html
{% extends 'classroom/base.html' %}

{% block title %}edit {{student.id}}{% endblock %}

{% block body %}
    <h1>Student info</h1>
    <form action="{% url 'classroom:update' student.id %}" method="POST">
        {% csrf_token %}
        <div>
            Name : <input type="text" id="name" name="name" value={{student.name}}>
        </div>
        <div>
            Age : <input type="number" id="age" name="age" value={{student.age}}>
        </div>
        <div>
            Major : <input type="text" id="major" name="major" value={{student.major}}>
        </div>
        <input type="submit" value="submit">
    </form>
{% endblock %}

06_django_advance/02_MY_RECAP/classroom/templates/classroom/index.html
{% extends 'classroom/base.html' %}

{% block title %}index{% endblock %}

{% block body %}
    <a href="{% url 'classroom:lists' %}">Click here</a>
{% endblock %}

06_django_advance/02_MY_RECAP/classroom/templates/classroom/lists.html
{% extends 'classroom/base.html' %}

{% block title %}lists{% endblock %}

{% block body %}
    <h1>Students</h1>
    <ul>
        {% for student in students %}
                <li>
                    <a href="{% url 'classroom:detail' student.id %}">
                        {{student.id}} | {{student.name}}
                    </a>
                </li>
        {% endfor %}
    </ul>
    <a href="{% url 'classroom:new' %}"><button>new</button></a>
{% endblock %}

06_django_advance/02_MY_RECAP/classroom/templates/classroom/new.html
{% extends 'classroom/base.html' %}

{% block title %}new{% endblock %}

{% block body %}
    <h1>Student info</h1>
    <form action="{% url 'classroom:create' %}" method="POST">
        {% csrf_token %}
        <div>
            Name : <input type="text" id="name" name="name">
        </div>
        <div>
            Age : <input type="number" id="age" name="age">
        </div>
        <div>
            Major : <input type="text" id="major" name="major">
        </div>
        <input type="submit" value="submit">
    </form>
{% endblock %}

06_django_advance/02_MY_RECAP/classroom/templates/classroom/template.html
{% extends 'classroom/base.html' %}

{% block title %}{% endblock %}

{% block body %}
{% endblock %}